--Господи, за что мне это?--
use RK2;

--Themes--
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(1,1,'Союз нерушимый')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(2,2,'Республик свободных')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(3,3,'Сплотила навеки')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(4,4,'Великая Русь')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(5,5,'Да здравствует')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(6,6,'Созданный волей народов')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(7,7,'Единый')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(8,8,'Могучий')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(9,9,'Советский')
INSERT dbo.Themes(ThemeID, Teacher,Theme)
VALUES(10,10,'Союз')

--Marks--
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(1,914,5,5)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(2,458,4,3)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(3,865,5,4)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(4,841, 3,3)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(5,945,4,4)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(6,364,3,5)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(7,577,4,5)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(8,457,5,5)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(9,896,3,4)
INSERT dbo.Marks(MarkID, MarkBookNumber, RepExamMark, DiplomaMark)
VALUES(10,874,5,4)