insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (1, 'Product Management', '255-192-3041', 'Christoph Carleton');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (2, 'Research and Development', '884-784-8612', 'Eydie Olyff');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (3, 'Marketing', '456-883-8742', 'Emmerich Dives');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (4, 'Human Resources', '151-163-1433', 'Ailbert McDermid');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (5, 'Business Development', '284-368-9914', 'Jacquie Petric');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (6, 'Human Resources', '626-869-4425', 'Robby Gemson');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (7, 'Legal', '221-942-4557', 'Courtney Patkin');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (8, 'Training', '414-460-9507', 'Valma Dowty');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (9, 'Training', '591-380-7127', 'Jephthah Pepall');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (10, 'Engineering', '698-219-5022', 'Benedetto Geeves');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (11, 'Accounting', '718-685-5736', 'Flossie Meneer');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (12, 'Sales', '872-569-9756', 'Lynde Winterbourne');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (13, 'Product Management', '361-183-7292', 'Jarrad Ramsbottom');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (14, 'Research and Development', '317-307-6599', 'Ailey Sepey');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (15, 'Product Management', '770-562-5062', 'Orel Precious');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (16, 'Research and Development', '606-401-9662', 'Patsy Cummings');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (17, 'Business Development', '634-438-1570', 'Aline Georgeson');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (18, 'Product Management', '390-503-1905', 'Edna Yakuntzov');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (19, 'Sales', '549-485-4398', 'Ree Hakes');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (20, 'Business Development', '557-335-0520', 'Aubrette Larroway');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (21, 'Sales', '913-154-7988', 'Kennith Grosier');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (22, 'Services', '355-422-8879', 'Granny Jeckell');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (23, 'Legal', '547-484-6898', 'Kendall Ramet');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (24, 'Marketing', '993-450-6406', 'Vito Roblin');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (25, 'Business Development', '985-319-8052', 'Maurise Bellam');
insert into Departments (id, DepartmentName, DepartmentPhone, Chief) values (26, 'Engineering', '653-353-6059', 'Devon Goodere');
