insert into Employees (id, Department, Status, FullName, Salary) values (1, 'Support', 'Senior Financial Analyst', 'Rey Schimon', 389);
insert into Employees (id, Department, Status, FullName, Salary) values (2, 'Training', 'Software Consultant', 'Amargo Karle', 950);
insert into Employees (id, Department, Status, FullName, Salary) values (3, 'Engineering', 'Community Outreach Specialist', 'Benedetta Reinbach', 203);
insert into Employees (id, Department, Status, FullName, Salary) values (4, 'Legal', 'Community Outreach Specialist', 'Carlos Gheorghie', 929);
insert into Employees (id, Department, Status, FullName, Salary) values (5, 'Business Development', 'Analog Circuit Design manager', 'Jo Reah', 487);
insert into Employees (id, Department, Status, FullName, Salary) values (6, 'Support', 'Developer II', 'Leelah Werendell', 657);
insert into Employees (id, Department, Status, FullName, Salary) values (7, 'Business Development', 'Technical Writer', 'Borg Neasham', 158);
insert into Employees (id, Department, Status, FullName, Salary) values (8, 'Training', 'Senior Quality Engineer', 'Stephi Domenc', 473);
insert into Employees (id, Department, Status, FullName, Salary) values (9, 'Product Management', 'Administrative Officer', 'Cody Allso', 315);
insert into Employees (id, Department, Status, FullName, Salary) values (10, 'Training', 'General Manager', 'Tomasine Goddman', 733);
insert into Employees (id, Department, Status, FullName, Salary) values (11, 'Product Management', 'Nurse Practicioner', 'Vasili Morratt', 623);
insert into Employees (id, Department, Status, FullName, Salary) values (12, 'Research and Development', 'Programmer Analyst IV', 'Sonya Curryer', 273);
insert into Employees (id, Department, Status, FullName, Salary) values (13, 'Marketing', 'Database Administrator IV', 'Silvio Jedrasik', 398);
insert into Employees (id, Department, Status, FullName, Salary) values (14, 'Services', 'Financial Advisor', 'Reinaldo Ceeley', 706);
insert into Employees (id, Department, Status, FullName, Salary) values (15, 'Marketing', 'Budget/Accounting Analyst II', 'Hurley Bunclark', 540);
insert into Employees (id, Department, Status, FullName, Salary) values (16, 'Business Development', 'Structural Analysis Engineer', 'Davon Dalgardno', 409);
insert into Employees (id, Department, Status, FullName, Salary) values (17, 'Engineering', 'Account Coordinator', 'Galen McMurdo', 971);
insert into Employees (id, Department, Status, FullName, Salary) values (18, 'Product Management', 'Registered Nurse', 'Mariann Clemmens', 982);
insert into Employees (id, Department, Status, FullName, Salary) values (19, 'Product Management', 'Account Coordinator', 'Lenna Verma', 616);
insert into Employees (id, Department, Status, FullName, Salary) values (20, 'Legal', 'Biostatistician II', 'Susy Geldart', 691);
insert into Employees (id, Department, Status, FullName, Salary) values (21, 'Marketing', 'Director of Sales', 'Ayn Battisson', 506);
insert into Employees (id, Department, Status, FullName, Salary) values (22, 'Support', 'Technical Writer', 'Brynn Bainbridge', 666);
insert into Employees (id, Department, Status, FullName, Salary) values (23, 'Services', 'Structural Engineer', 'Pooh Gostyke', 569);
insert into Employees (id, Department, Status, FullName, Salary) values (24, 'Engineering', 'Speech Pathologist', 'Ailene Cool', 207);
insert into Employees (id, Department, Status, FullName, Salary) values (25, 'Business Development', 'Executive Secretary', 'Carma Jojic', 539);
insert into Employees (id, Department, Status, FullName, Salary) values (26, 'Support', 'Financial Advisor', 'Gunther Pulfer', 239);
