insert into Medicine (id, Name, Instruction, Price) values (1, 'Para Grass Pollen', 'Bzkpzvpdyjmzrnfndfju', 338);
insert into Medicine (id, Name, Instruction, Price) values (2, 'Candesartan cilexetil', 'Vcbixoyrjkfvmttiskgg', 634);
insert into Medicine (id, Name, Instruction, Price) values (3, 'suboxone', 'Lwbukyenvghnykcsjatk', 139);
insert into Medicine (id, Name, Instruction, Price) values (4, 'GRAPHITES', 'Ovycvickjfluhqvwwotb', 215);
insert into Medicine (id, Name, Instruction, Price) values (5, 'KINERASE', 'Ufzyreayqllluxhsyelb', 432);
insert into Medicine (id, Name, Instruction, Price) values (6, 'Kaletra', 'Jiwpgoyoxetjqtzdhumh', 725);
insert into Medicine (id, Name, Instruction, Price) values (7, 'SUMATRIPTAN', 'Oxrcwbsqonenmfonwkoe', 323);
insert into Medicine (id, Name, Instruction, Price) values (8, 'Cefprozil', 'Tvgmnegdsuvmmsytttab', 687);
insert into Medicine (id, Name, Instruction, Price) values (9, 'Lobelia Quercus', 'Dppxfvhkecaqkavfkgpk', 292);
insert into Medicine (id, Name, Instruction, Price) values (10, 'Bisoprolol Fumarate', 'Puijrfycenjoajxoqsic', 131);
insert into Medicine (id, Name, Instruction, Price) values (11, 'Carbinoxamine Maleate', 'Hwxksodcphloupdrmlgm', 545);
insert into Medicine (id, Name, Instruction, Price) values (12, 'CAFFEINE CITRATE', 'Uumqvwpalwqwwdhmptdi', 554);
insert into Medicine (id, Name, Instruction, Price) values (13, 'Suave', 'Etzalbknhpyjbsbgkpnb', 745);
insert into Medicine (id, Name, Instruction, Price) values (14, 'Rohto Hydra', 'Pqyramgmvtuvvtwmtzad', 492);
insert into Medicine (id, Name, Instruction, Price) values (15, 'Rexall Arthritis Pain', 'Amnjtvuzmrazsbohlesb', 783);
insert into Medicine (id, Name, Instruction, Price) values (16, 'OXYGEN', 'Xbxarsnygbfjveelnmis', 719);
insert into Medicine (id, Name, Instruction, Price) values (17, 'SUPERDEFENSE DAILY DEFENSE MOISTURIZER BROAD SPECTRUM SPF20 (COMBINATION OILY - OILY)', 'Zgdhkaaacxgsdbfbvdcn', 212);
insert into Medicine (id, Name, Instruction, Price) values (18, 'Eczema Rescue', 'Zukxprhgnwjsuilamukb', 567);
insert into Medicine (id, Name, Instruction, Price) values (19, 'Montelukast Sodium', 'Hbvfheynpmftlrskrfpe', 155);
insert into Medicine (id, Name, Instruction, Price) values (20, 'CVS Alcohol Prep', 'Hbrkmxnwpurndanjixgy', 222);
insert into Medicine (id, Name, Instruction, Price) values (21, 'VALACYCLOVIR', 'Iwwjdozvamvdpvwxpckl', 251);
insert into Medicine (id, Name, Instruction, Price) values (22, 'Antispetic', 'Ugowupofyemvrfghtmgh', 983);
insert into Medicine (id, Name, Instruction, Price) values (23, 'Lipitor', 'Umjjhsotnxbgkwsurozl', 142);
insert into Medicine (id, Name, Instruction, Price) values (24, 'Cyclobenzaprine Hydrochloride', 'Qsdeadzqtoffechzmqzb', 939);
insert into Medicine (id, Name, Instruction, Price) values (25, 'FNG', 'Azjihkudvhnzxcqkhfvf', 523);
insert into Medicine (id, Name, Instruction, Price) values (26, 'Indomethacin', 'Hpxfwxexxjoexhzwfizx', 535);
